/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.retry.annotation.EnableRetry;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.context.annotation.Bean;

import org.example.repository.PublicationRepository;
import org.example.model.Publication;

@SpringBootApplication
@EnableAspectJAutoProxy
@EnableRetry
public class App {

    public static void main(String[] args) {
	    SpringApplication.run(App.class, args);
    }

    @Bean
    public ApplicationRunner init(PublicationRepository repo) {
	    return args -> {
		    var pub = new Publication();
		    repo.save(pub).subscribe();
	    };
    }
}
